/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDataSource */

#ifndef _Included_NativeDataSource
#define _Included_NativeDataSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDataSource
 * Method:    calibrate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeDataSource_calibrate
  (JNIEnv *, jclass);

/*
 * Class:     NativeDataSource
 * Method:    start
 * Signature: (Ljava/nio/IntBuffer;ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_NativeDataSource_start
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
